///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DataImportAndLoad
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DataImportAndLoadRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("f1452eba-c83e-42c8-9d6c-0e9801d48e51")]
    public partial class DataImportAndLoadRepository : RepoGenBaseFolder
    {
        static DataImportAndLoadRepository instance = new DataImportAndLoadRepository();
        DataImportAndLoadRepositoryFolders.Form7DSurgicalSoftwareSpineModuleAppFolder _form7dsurgicalsoftwarespinemodule;

        /// <summary>
        /// Gets the singleton class instance representing the DataImportAndLoadRepository element repository.
        /// </summary>
        [RepositoryFolder("f1452eba-c83e-42c8-9d6c-0e9801d48e51")]
        public static DataImportAndLoadRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DataImportAndLoadRepository() 
            : base("DataImportAndLoadRepository", "/", null, 0, false, "f1452eba-c83e-42c8-9d6c-0e9801d48e51", ".\\RepositoryImages\\DataImportAndLoadRepositoryf1452eba.rximgres")
        {
            _form7dsurgicalsoftwarespinemodule = new DataImportAndLoadRepositoryFolders.Form7DSurgicalSoftwareSpineModuleAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f1452eba-c83e-42c8-9d6c-0e9801d48e51")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Form7DSurgicalSoftwareSpineModule folder.
        /// </summary>
        [RepositoryFolder("23d6a5e1-ab9c-4b39-8f02-f02fa6c12134")]
        public virtual DataImportAndLoadRepositoryFolders.Form7DSurgicalSoftwareSpineModuleAppFolder Form7DSurgicalSoftwareSpineModule
        {
            get { return _form7dsurgicalsoftwarespinemodule; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class DataImportAndLoadRepositoryFolders
    {
        /// <summary>
        /// The Form7DSurgicalSoftwareSpineModuleAppFolder folder.
        /// </summary>
        [RepositoryFolder("23d6a5e1-ab9c-4b39-8f02-f02fa6c12134")]
        public partial class Form7DSurgicalSoftwareSpineModuleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selectpatientdataforthisprocedureInfo;

            /// <summary>
            /// Creates a new Form7DSurgicalSoftwareSpineModule  folder.
            /// </summary>
            public Form7DSurgicalSoftwareSpineModuleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form7DSurgicalSoftwareSpineModule", "/form[@title~'^7D\\ Surgical\\ Software\\ -\\ Sp']", parentFolder, 30000, null, true, "23d6a5e1-ab9c-4b39-8f02-f02fa6c12134", "")
            {
                _selectpatientdataforthisprocedureInfo = new RepoItemInfo(this, "SelectPatientDataForThisProcedure", "?/?/list[@automationid='MessageBar']/text[@caption~'^Select\\ patient\\ data\\ for\\ t']", 30000, null, "3b87049f-f924-4d13-aff2-7090a683dd02");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("23d6a5e1-ab9c-4b39-8f02-f02fa6c12134")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("23d6a5e1-ab9c-4b39-8f02-f02fa6c12134")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectPatientDataForThisProcedure item.
            /// </summary>
            [RepositoryItem("3b87049f-f924-4d13-aff2-7090a683dd02")]
            public virtual Ranorex.Text SelectPatientDataForThisProcedure
            {
                get
                {
                    return _selectpatientdataforthisprocedureInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SelectPatientDataForThisProcedure item info.
            /// </summary>
            [RepositoryItemInfo("3b87049f-f924-4d13-aff2-7090a683dd02")]
            public virtual RepoItemInfo SelectPatientDataForThisProcedureInfo
            {
                get
                {
                    return _selectpatientdataforthisprocedureInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}